sudo: false
dist: trusty
language: node_js
node_js:
- 10
cache:
  directories:
  - node_modules
before_script:
- chmod +x scripts/docs
script:
- npm run lint
- npm run cover -- --runInBand
after_script:
- npm run report-coverage
after_success:
- scripts/docs
env: $GITHUB_TOKEN
branches:
  only:
  - master
  - "/^\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
before_deploy:
- echo 'Preparing to publish'
- npm run build
deploy:
  provider: npm
  email: ap311036@gmail.com
  api_key: $NPM_API_KEY
  skip_cleanup: true
  on:
    tags: true